#!/usr/bin/env bash
# Генерирует самоподписанный сертификат и ключ на хосте и создаёт C-заголовок
# для встраивания в прошивку (USE_HTTPS_PRECOMPILED_CERT).
# Требуется: openssl, xxd.
# Использование: из корня проекта: bash scripts/generate_https_cert.sh

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$PROJECT_DIR/include"
TMP_DIR="${TMPDIR:-/tmp}/smarthterm_cert_$$"
mkdir -p "$TMP_DIR"
mkdir -p "$OUT_DIR"
trap 'rm -rf "$TMP_DIR"' EXIT

CERT_PEM="$TMP_DIR/cert.pem"
KEY_PEM="$TMP_DIR/key.pem"
CERT_DER="$TMP_DIR/cert.der"
KEY_DER="$TMP_DIR/key.der"
HEADER="$OUT_DIR/cert_embed.h"

SUBJ="/CN=SmartTherm.local/O=SmartTherm/C=RU"
VALID_DAYS=3650

echo "Generating RSA 2048 key and self-signed certificate..."
openssl req -x509 -newkey rsa:2048 -keyout "$KEY_PEM" -out "$CERT_PEM" \
  -days "$VALID_DAYS" -nodes -subj "$SUBJ" \
  -addext "subjectAltName=DNS:SmartTherm.local,DNS:*.local,IP:192.168.4.1" 2>/dev/null || \
openssl req -x509 -newkey rsa:2048 -keyout "$KEY_PEM" -out "$CERT_PEM" \
  -days "$VALID_DAYS" -nodes -subj "$SUBJ"

openssl x509 -inform PEM -outform DER -in "$CERT_PEM" -out "$CERT_DER"
openssl rsa -inform PEM -outform DER -in "$KEY_PEM" -out "$KEY_DER"

CERT_LEN=$(wc -c < "$CERT_DER")
KEY_LEN=$(wc -c < "$KEY_DER")
if [ "$CERT_LEN" -gt 65535 ] || [ "$KEY_LEN" -gt 65535 ]; then
  echo "Error: cert or key too large for uint16_t (64K limit)" >&2
  exit 1
fi

# Generate C header (use Python; xxd often not in PATH on minimal systems)
python3 - "$CERT_DER" "$KEY_DER" "$CERT_LEN" "$KEY_LEN" "$HEADER" << 'PY'
import sys
def bytes_to_c_array(path, name, len_name):
    with open(path, "rb") as f:
        data = f.read()
    lines = ["static const unsigned char %s[] = {" % name]
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append("  " + ", ".join("0x%02x" % b for b in chunk) + ",")
    lines.append("};")
    lines.append("static const unsigned int %s = %u;" % (len_name, len(data)))
    return "\n".join(lines)
cert_der, key_der, cert_len, key_len, out_path = sys.argv[1], sys.argv[2], int(sys.argv[3]), int(sys.argv[4]), sys.argv[5]
with open(out_path, "w") as f:
    f.write("#ifndef CERT_EMBED_H_\n#define CERT_EMBED_H_\n")
    f.write("/* Auto-generated by scripts/generate_https_cert.sh - do not edit */\n")
    f.write("#if defined(USE_HTTPS) && defined(USE_HTTPS_PRECOMPILED_CERT)\n\n")
    f.write("/* Certificate (DER), %u bytes */\n" % cert_len)
    f.write(bytes_to_c_array(cert_der, "https_cert_der", "https_cert_der_len"))
    f.write("\n\n/* Private key (DER), %u bytes */\n" % key_len)
    f.write(bytes_to_c_array(key_der, "https_key_der", "https_key_der_len"))
    f.write("\n\n#endif\n#endif /* CERT_EMBED_H_ */\n")
PY

echo "Written $HEADER (cert $CERT_LEN bytes, key $KEY_LEN bytes)."
